### ISSUE TITLE
Is Svelte 5 supported?

### ISSUE THREAD

**Issue by HuakunShen** [svelte-u/docs#2]

**Comment by Mohamed-Kaizen** [comment]
Hi @HuakunShen,

Great news! Svelte 5 works perfectly with the code you provided. Here's an example to demonstrate: [link to Svelte Playground example](https://svelte.dev/playground/hello-world?version=5.1.14#H4sIAAAAAAAAA42QwWqEMBCGX2UIPSjr1u5VVFrooX2BXmpZYpxF2TiRZFxbJO9erGvYQg_NaZj_-yfzzyxI9igy8YJaG5iM1Q1E2HSMTSwSceo0OpG9z4K_hoVbGiLZXE_DcO8uqHnp1dLhX31liJHYiUzkTtlu4LIiAICuH4xlmCfJqpW1Rg8na3qoxKO74Ji6VlpsKlHRymtkIJyOF6lHTIxu1mqTTyMp7gyBklrXUp2jY2ASOAZnDPNq2F5QoLjBfjNh0sLcfL1ofttAGXIMP3GwgQJCsOghCVvFFeVpuENFeT0yGwJDmdKdOhdzFENRwt11zm7ny1dSFnskztOV_pdzv_flM_7pbG16LQ4l4QRvS5oM5pDe52l7KAO5cEY3gQsX2LiKRCIYP1lkbEf0H_4bfKzkS1sCAAA=).

Now, if your original question was whether `Svelte Runs` itself will  be supported, then the answer is no.
